apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: overlay.csi.io
  labels:
    app.kubernetes.io/instance: overlay.csi.io
    app.kubernetes.io/part-of: csi-driver-overlay
    app.kubernetes.io/name: overlay.csi.io
    app.kubernetes.io/component: csi-driver
spec:
  # Overlay driver only supports ephemeral inline volumes
  volumeLifecycleModes:
  - Ephemeral
  # Pod info is required to construct volume paths
  podInfoOnMount: true
  # Kubernetes may use fsGroup to change permissions and ownership
  # of the volume to match user requested fsGroup in the pod's SecurityPolicy
  fsGroupPolicy: File
